export const placeholderImages = [
    {
      full: "https://picsum.photos/id/1011/600",
      thumb: "https://picsum.photos/id/1011/300",
      title: "Placeholder Image 1",
      description: "This is a placeholder description.",
      alt: "Placeholder Image 1",
      category: "nature",
      date: "2025-07-01",
    },
    {
      full: "https://picsum.photos/id/1025/600",
      thumb: "https://picsum.photos/id/1025/300",
      title: "Placeholder Image 2",
      description: "Another placeholder description.",
      alt: "Placeholder Image 2",
      category: "urban",
      date: "2025-06-15",
    },
    {
      full: "https://picsum.photos/id/1003/600",
      thumb: "https://picsum.photos/id/1003/300",
      title: "Placeholder Image 3",
      description: "Sample placeholder text.",
      alt: "Placeholder Image 3",
      category: "portraits",
      date: "2025-06-01",
    },
    {
      full: "https://picsum.photos/id/1041/600",
      thumb: "https://picsum.photos/id/1041/300",
      title: "Placeholder Image 4",
      description: "Another sample.",
      alt: "Placeholder Image 4",
      category: "nature",
      date: "2025-05-20",
    },
    {
      full: "https://picsum.photos/id/1031/600",
      thumb: "https://picsum.photos/id/1031/300",
      title: "Placeholder Image 5",
      description: "Urban landscape.",
      alt: "Placeholder Image 5",
      category: "urban",
      date: "2025-05-10",
    },
    {
      full: "https://picsum.photos/id/1051/600",
      thumb: "https://picsum.photos/id/1051/300",
      title: "Placeholder Image 6",
      description: "Portrait with dramatic lighting.",
      alt: "Placeholder Image 6",
      category: "portraits",
      date: "2025-05-05",
    },
    {
      full: "https://picsum.photos/id/1061/600",
      thumb: "https://picsum.photos/id/1061/300",
      title: "Placeholder Image 7",
      description: "Sunset in the city.",
      alt: "Placeholder Image 7",
      category: "urban",
      date: "2025-04-25",
    },
  ];

  export const INITIAL_VISIBLE_COUNT = 6;